#############################################################################
# Makefile for building: tke
# Generated by qmake (2.01a) (Qt 4.6.3) on: ?? 12. ??? 12:31:29 2014
# Project:  tke.pro
# Template: subdirs
# Command: c:\Qt\4.6.3\bin\qmake.exe -win32 -o Makefile tke.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\Qt\4.6.3\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-tkeAbonent \
		sub-tkeOrganizacii \
		sub-install-configure \
		sub-tkeQtSqlBrowser

tkeAbonent\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tkeAbonent\ $(MKDIR) tkeAbonent\ 
	cd tkeAbonent\ && $(QMAKE) e:\udev\tke\tkeAbonent\tkeAbonent.pro -win32 -o $(MAKEFILE)
sub-tkeAbonent-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tkeAbonent\ $(MKDIR) tkeAbonent\ 
	cd tkeAbonent\ && $(QMAKE) e:\udev\tke\tkeAbonent\tkeAbonent.pro -win32 -o $(MAKEFILE)
sub-tkeAbonent: tkeAbonent\$(MAKEFILE) FORCE
	cd tkeAbonent\ && $(MAKE) -f $(MAKEFILE)
sub-tkeAbonent-make_default: tkeAbonent\$(MAKEFILE) FORCE
	cd tkeAbonent\ && $(MAKE) -f $(MAKEFILE) 
sub-tkeAbonent-make_first: tkeAbonent\$(MAKEFILE) FORCE
	cd tkeAbonent\ && $(MAKE) -f $(MAKEFILE) first
sub-tkeAbonent-all: tkeAbonent\$(MAKEFILE) FORCE
	cd tkeAbonent\ && $(MAKE) -f $(MAKEFILE) all
sub-tkeAbonent-clean: tkeAbonent\$(MAKEFILE) FORCE
	cd tkeAbonent\ && $(MAKE) -f $(MAKEFILE) clean
sub-tkeAbonent-distclean: tkeAbonent\$(MAKEFILE) FORCE
	cd tkeAbonent\ && $(MAKE) -f $(MAKEFILE) distclean
sub-tkeAbonent-install_subtargets: tkeAbonent\$(MAKEFILE) FORCE
	cd tkeAbonent\ && $(MAKE) -f $(MAKEFILE) install
sub-tkeAbonent-uninstall_subtargets: tkeAbonent\$(MAKEFILE) FORCE
	cd tkeAbonent\ && $(MAKE) -f $(MAKEFILE) uninstall
tkeOrganizacii\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tkeOrganizacii\ $(MKDIR) tkeOrganizacii\ 
	cd tkeOrganizacii\ && $(QMAKE) e:\udev\tke\tkeOrganizacii\tkeOrganizacii.pro -win32 -o $(MAKEFILE)
sub-tkeOrganizacii-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tkeOrganizacii\ $(MKDIR) tkeOrganizacii\ 
	cd tkeOrganizacii\ && $(QMAKE) e:\udev\tke\tkeOrganizacii\tkeOrganizacii.pro -win32 -o $(MAKEFILE)
sub-tkeOrganizacii: tkeOrganizacii\$(MAKEFILE) FORCE
	cd tkeOrganizacii\ && $(MAKE) -f $(MAKEFILE)
sub-tkeOrganizacii-make_default: tkeOrganizacii\$(MAKEFILE) FORCE
	cd tkeOrganizacii\ && $(MAKE) -f $(MAKEFILE) 
sub-tkeOrganizacii-make_first: tkeOrganizacii\$(MAKEFILE) FORCE
	cd tkeOrganizacii\ && $(MAKE) -f $(MAKEFILE) first
sub-tkeOrganizacii-all: tkeOrganizacii\$(MAKEFILE) FORCE
	cd tkeOrganizacii\ && $(MAKE) -f $(MAKEFILE) all
sub-tkeOrganizacii-clean: tkeOrganizacii\$(MAKEFILE) FORCE
	cd tkeOrganizacii\ && $(MAKE) -f $(MAKEFILE) clean
sub-tkeOrganizacii-distclean: tkeOrganizacii\$(MAKEFILE) FORCE
	cd tkeOrganizacii\ && $(MAKE) -f $(MAKEFILE) distclean
sub-tkeOrganizacii-install_subtargets: tkeOrganizacii\$(MAKEFILE) FORCE
	cd tkeOrganizacii\ && $(MAKE) -f $(MAKEFILE) install
sub-tkeOrganizacii-uninstall_subtargets: tkeOrganizacii\$(MAKEFILE) FORCE
	cd tkeOrganizacii\ && $(MAKE) -f $(MAKEFILE) uninstall
install\configure\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) install\configure\ $(MKDIR) install\configure\ 
	cd install\configure\ && $(QMAKE) e:\udev\tke\install\configure\configure.pro -win32 -o $(MAKEFILE)
sub-install-configure-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) install\configure\ $(MKDIR) install\configure\ 
	cd install\configure\ && $(QMAKE) e:\udev\tke\install\configure\configure.pro -win32 -o $(MAKEFILE)
sub-install-configure: install\configure\$(MAKEFILE) FORCE
	cd install\configure\ && $(MAKE) -f $(MAKEFILE)
sub-install-configure-make_default: install\configure\$(MAKEFILE) FORCE
	cd install\configure\ && $(MAKE) -f $(MAKEFILE) 
sub-install-configure-make_first: install\configure\$(MAKEFILE) FORCE
	cd install\configure\ && $(MAKE) -f $(MAKEFILE) first
sub-install-configure-all: install\configure\$(MAKEFILE) FORCE
	cd install\configure\ && $(MAKE) -f $(MAKEFILE) all
sub-install-configure-clean: install\configure\$(MAKEFILE) FORCE
	cd install\configure\ && $(MAKE) -f $(MAKEFILE) clean
sub-install-configure-distclean: install\configure\$(MAKEFILE) FORCE
	cd install\configure\ && $(MAKE) -f $(MAKEFILE) distclean
sub-install-configure-install_subtargets: install\configure\$(MAKEFILE) FORCE
	cd install\configure\ && $(MAKE) -f $(MAKEFILE) install
sub-install-configure-uninstall_subtargets: install\configure\$(MAKEFILE) FORCE
	cd install\configure\ && $(MAKE) -f $(MAKEFILE) uninstall
tkeQtSqlBrowser\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tkeQtSqlBrowser\ $(MKDIR) tkeQtSqlBrowser\ 
	cd tkeQtSqlBrowser\ && $(QMAKE) e:\udev\tke\tkeQtSqlBrowser\tkeQtSqlBrowser.pro -win32 -o $(MAKEFILE)
sub-tkeQtSqlBrowser-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tkeQtSqlBrowser\ $(MKDIR) tkeQtSqlBrowser\ 
	cd tkeQtSqlBrowser\ && $(QMAKE) e:\udev\tke\tkeQtSqlBrowser\tkeQtSqlBrowser.pro -win32 -o $(MAKEFILE)
sub-tkeQtSqlBrowser: tkeQtSqlBrowser\$(MAKEFILE) FORCE
	cd tkeQtSqlBrowser\ && $(MAKE) -f $(MAKEFILE)
sub-tkeQtSqlBrowser-make_default: tkeQtSqlBrowser\$(MAKEFILE) FORCE
	cd tkeQtSqlBrowser\ && $(MAKE) -f $(MAKEFILE) 
sub-tkeQtSqlBrowser-make_first: tkeQtSqlBrowser\$(MAKEFILE) FORCE
	cd tkeQtSqlBrowser\ && $(MAKE) -f $(MAKEFILE) first
sub-tkeQtSqlBrowser-all: tkeQtSqlBrowser\$(MAKEFILE) FORCE
	cd tkeQtSqlBrowser\ && $(MAKE) -f $(MAKEFILE) all
sub-tkeQtSqlBrowser-clean: tkeQtSqlBrowser\$(MAKEFILE) FORCE
	cd tkeQtSqlBrowser\ && $(MAKE) -f $(MAKEFILE) clean
sub-tkeQtSqlBrowser-distclean: tkeQtSqlBrowser\$(MAKEFILE) FORCE
	cd tkeQtSqlBrowser\ && $(MAKE) -f $(MAKEFILE) distclean
sub-tkeQtSqlBrowser-install_subtargets: tkeQtSqlBrowser\$(MAKEFILE) FORCE
	cd tkeQtSqlBrowser\ && $(MAKE) -f $(MAKEFILE) install
sub-tkeQtSqlBrowser-uninstall_subtargets: tkeQtSqlBrowser\$(MAKEFILE) FORCE
	cd tkeQtSqlBrowser\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: tke.pro  c:/Qt/4.6.3/mkspecs/default/qmake.conf c:/Qt/4.6.3/mkspecs/qconfig.pri \
		c:/Qt/4.6.3/mkspecs/features/qt_functions.prf \
		c:/Qt/4.6.3/mkspecs/features/qt_config.prf \
		c:/Qt/4.6.3/mkspecs/features/exclusive_builds.prf \
		c:/Qt/4.6.3/mkspecs/features/default_pre.prf \
		c:/Qt/4.6.3/mkspecs/features/win32/default_pre.prf \
		c:/Qt/4.6.3/mkspecs/features/release.prf \
		c:/Qt/4.6.3/mkspecs/features/default_post.prf \
		c:/Qt/4.6.3/mkspecs/features/win32/default_post.prf \
		c:/Qt/4.6.3/mkspecs/features/win32/rtti.prf \
		c:/Qt/4.6.3/mkspecs/features/win32/exceptions.prf \
		c:/Qt/4.6.3/mkspecs/features/win32/stl.prf \
		c:/Qt/4.6.3/mkspecs/features/shared.prf \
		c:/Qt/4.6.3/mkspecs/features/warn_on.prf \
		c:/Qt/4.6.3/mkspecs/features/qt.prf \
		c:/Qt/4.6.3/mkspecs/features/win32/thread.prf \
		c:/Qt/4.6.3/mkspecs/features/moc.prf \
		c:/Qt/4.6.3/mkspecs/features/win32/windows.prf \
		c:/Qt/4.6.3/mkspecs/features/resources.prf \
		c:/Qt/4.6.3/mkspecs/features/uic.prf \
		c:/Qt/4.6.3/mkspecs/features/yacc.prf \
		c:/Qt/4.6.3/mkspecs/features/lex.prf \
		c:/Qt/4.6.3/mkspecs/features/incredibuild_xge.prf \
		c:/Qt/4.6.3/mkspecs/features/include_source_dir.prf
	$(QMAKE) -win32 -o Makefile tke.pro
c:\Qt\4.6.3\mkspecs\qconfig.pri:
c:\Qt\4.6.3\mkspecs\features\qt_functions.prf:
c:\Qt\4.6.3\mkspecs\features\qt_config.prf:
c:\Qt\4.6.3\mkspecs\features\exclusive_builds.prf:
c:\Qt\4.6.3\mkspecs\features\default_pre.prf:
c:\Qt\4.6.3\mkspecs\features\win32\default_pre.prf:
c:\Qt\4.6.3\mkspecs\features\release.prf:
c:\Qt\4.6.3\mkspecs\features\default_post.prf:
c:\Qt\4.6.3\mkspecs\features\win32\default_post.prf:
c:\Qt\4.6.3\mkspecs\features\win32\rtti.prf:
c:\Qt\4.6.3\mkspecs\features\win32\exceptions.prf:
c:\Qt\4.6.3\mkspecs\features\win32\stl.prf:
c:\Qt\4.6.3\mkspecs\features\shared.prf:
c:\Qt\4.6.3\mkspecs\features\warn_on.prf:
c:\Qt\4.6.3\mkspecs\features\qt.prf:
c:\Qt\4.6.3\mkspecs\features\win32\thread.prf:
c:\Qt\4.6.3\mkspecs\features\moc.prf:
c:\Qt\4.6.3\mkspecs\features\win32\windows.prf:
c:\Qt\4.6.3\mkspecs\features\resources.prf:
c:\Qt\4.6.3\mkspecs\features\uic.prf:
c:\Qt\4.6.3\mkspecs\features\yacc.prf:
c:\Qt\4.6.3\mkspecs\features\lex.prf:
c:\Qt\4.6.3\mkspecs\features\incredibuild_xge.prf:
c:\Qt\4.6.3\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -win32 -o Makefile tke.pro

qmake_all: sub-tkeAbonent-qmake_all sub-tkeOrganizacii-qmake_all sub-install-configure-qmake_all sub-tkeQtSqlBrowser-qmake_all FORCE

make_default: sub-tkeAbonent-make_default sub-tkeOrganizacii-make_default sub-install-configure-make_default sub-tkeQtSqlBrowser-make_default FORCE
make_first: sub-tkeAbonent-make_first sub-tkeOrganizacii-make_first sub-install-configure-make_first sub-tkeQtSqlBrowser-make_first FORCE
all: sub-tkeAbonent-all sub-tkeOrganizacii-all sub-install-configure-all sub-tkeQtSqlBrowser-all FORCE
clean: sub-tkeAbonent-clean sub-tkeOrganizacii-clean sub-install-configure-clean sub-tkeQtSqlBrowser-clean FORCE
distclean: sub-tkeAbonent-distclean sub-tkeOrganizacii-distclean sub-install-configure-distclean sub-tkeQtSqlBrowser-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-tkeAbonent-install_subtargets sub-tkeOrganizacii-install_subtargets sub-install-configure-install_subtargets sub-tkeQtSqlBrowser-install_subtargets FORCE
uninstall_subtargets: sub-tkeAbonent-uninstall_subtargets sub-tkeOrganizacii-uninstall_subtargets sub-install-configure-uninstall_subtargets sub-tkeQtSqlBrowser-uninstall_subtargets FORCE

sub-tkeAbonent-check: tkeAbonent\$(MAKEFILE)
	cd tkeAbonent\ && $(MAKE) check
sub-tkeOrganizacii-check: tkeOrganizacii\$(MAKEFILE)
	cd tkeOrganizacii\ && $(MAKE) check
sub-install-configure-check: install\configure\$(MAKEFILE)
	cd install\configure\ && $(MAKE) check
sub-tkeQtSqlBrowser-check: tkeQtSqlBrowser\$(MAKEFILE)
	cd tkeQtSqlBrowser\ && $(MAKE) check
check: sub-tkeAbonent-check sub-tkeOrganizacii-check sub-install-configure-check sub-tkeQtSqlBrowser-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

