######################################################################
# Automatically generated by qmake (2.01a) ?? 4. ??? 19:36:22 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += UReplaceStringsParser.h
SOURCES += main.cpp UReplaceStringsParser.cpp

CONFIG += console

DESTDIR +=   ./
